version: '3.8'

services:
  web:
    container_name: twitter
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /static:/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_NAME: ${POSTGRES_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  migrate:
    container_name: migration
    build:
      context: .
      dockerfile: Dockerfile
    command: alembic upgrade head
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /static:/static
    restart: always
    depends_on:
      - web

volumes:
  postgres-data:
  static: